# Meta Data for SEO

## Homepage
title = "Astral"
titleSeparator = "-"
titleAddition = "Docs"
description = "Easily create a custom Discord bot with Astral."

## Documentation
# docsVersion = "0.3"

## Open Graph
images = ["AstralOG.png"]
ogLocale = "en_US"
domainTLD = "docs.astralapp.io"
titleHome = "Astral Documentation"

## Twitter Cards
twitterSite = "@astral_bots"
twitterCreator = "@jack__merrill"

## JSON-LD
# schemaType = "Person"
schemaType = "Organization"
schemaName = "Astral Services"
schemaAuthor = "Jack Merrill"
schemaAuthorTwitter = "https://twitter.com/jack__merrill"
schemaAuthorGitHub = "https://github.com/jackmerrill"
schemaLocale = "en-US"
schemaLogo = "AstralLogo.png"
schemaLogoWidth = 512
schemaLogoHeight = 512
schemaImage = "AstralOG.png"
schemaImageWidth = 1280
schemaImageHeight = 640
schemaTwitter = "https://twitter.com/astral_bots"
schemaLinkedIn = ""
schemaGitHub = "https://github.com/astralservices/docs"
schemaSection = "blog"

## Sitelinks Search Box
siteLinksSearchBox = false

## Chrome Browser
themeColor = "#fff"

# Images
quality = 85
bgColor = "#fff"
landscapePhotoWidths = [900, 800, 700, 600, 500]
portraitPhotoWidths = [800, 700, 600, 500]
lqipWidth = "20x"
smallLimit = "300"

# Footer
footer = "Powered by <a class=\"text-muted\" href=\"https://getdoks.org/\">Doks</a>"

# Feed
copyRight = "Copyright (c) 2022 Astral Services"

# Alert
alert = false
alertDismissable = true
# alertText = "Introducing the Doks child theme, several DX + UX updates, and more! <a class=\"alert-link stretched-link\" href=\"https://getdoks.org/blog/doks-v0.2/\" target=\"_blank\" rel=\"noopener\">Check out Doks v0.2</a>"
alertText = "This documentation is currently a work in progress! Please be patient with us!"

# Edit Page
# repoHost [Github | Gitea | GitLab | Bitbucket | BitbucketServer ] is used for building the edit link based on git hoster
repoHost = "GitHub"
#repoHost = "Gitea"
docsRepo = "https://github.com/astralservices/docs"
docsRepoBranch = "master"
docsRepoSubPath = ""
editPage = true
lastMod = true

[options]
  lazySizes = true
  clipBoard = true
  instantPage = true
  flexSearch = true
  darkMode = true
  bootStrapJs = true
  breadCrumb = false
  highLight = true
  kaTex = false
  multilingualMode = false
  docsVersioning = false
  fullWidth = false

[menu]
  [menu.section]
    auto = false
    collapsibleSidebar = true
